"""Validation-owned temporal and robustness primitives.

The names documented in ``PUBLIC_PYTHON_API.md`` are the supported consumer
surface for constructing validation evidence and evaluating it; imports from
the implementation submodules remain private.
"""

from quant_platform.data.models import CoverageInterval, Instant

from .availability import (
    CandidateClassification,
    CandidateClassificationResult,
    DependencyCutoffRole,
    DependencyEvidence,
    DependencyLifecycle,
    DependencyMaturity,
    Embargo,
    ValidationCandidate,
    classify_candidate,
)
from .labels import (
    LABEL_DEFINITION_IDENTITY_DOMAIN,
    LABEL_RESULT_IDENTITY_DOMAIN,
    LabelCensoringPolicy,
    LabelDefinition,
    LabelError,
    LabelResult,
    LabelStatus,
    LabelTransformKind,
    OutcomeEvidence,
    OutcomeState,
    as_training_dependency_evidence,
    evaluate_label,
)
from .lockbox import (
    LOCKBOX_IDENTITY_DOMAIN,
    Lockbox,
    LockboxError,
    LockboxVisibility,
)
from .robustness import (
    DSR_SPEC_VERSION,
    NUMERICAL_POLICY_ID,
    PANEL_IDENTITY_DOMAIN,
    PBO_SPEC_VERSION,
    SAMPLING_MODEL_IID_V1,
    CSCVSplitEvidence,
    ComparableTrialPanel,
    DSRResult,
    EffectiveTrialCountEvidence,
    EvaluationStatus,
    MomentsResult,
    PBOResult,
    RobustnessError,
    SharpeResult,
    compute_moments_v1,
    compute_sharpe_v1,
    evaluate_dsr_v1,
    evaluate_pbo_v1,
)
from .walk_forward import (
    WalkForwardFold,
    WalkForwardScheduleSpec,
    build_walk_forward_folds,
)

__all__ = [
    "CandidateClassification",
    "CandidateClassificationResult",
    "CSCVSplitEvidence",
    "ComparableTrialPanel",
    "CoverageInterval",
    "DSRResult",
    "DSR_SPEC_VERSION",
    "DependencyCutoffRole",
    "DependencyEvidence",
    "DependencyLifecycle",
    "DependencyMaturity",
    "EffectiveTrialCountEvidence",
    "Embargo",
    "EvaluationStatus",
    "Instant",
    "LABEL_DEFINITION_IDENTITY_DOMAIN",
    "LABEL_RESULT_IDENTITY_DOMAIN",
    "LOCKBOX_IDENTITY_DOMAIN",
    "LabelCensoringPolicy",
    "LabelDefinition",
    "LabelError",
    "LabelResult",
    "LabelStatus",
    "LabelTransformKind",
    "Lockbox",
    "LockboxError",
    "LockboxVisibility",
    "MomentsResult",
    "NUMERICAL_POLICY_ID",
    "OutcomeEvidence",
    "OutcomeState",
    "PANEL_IDENTITY_DOMAIN",
    "PBOResult",
    "PBO_SPEC_VERSION",
    "RobustnessError",
    "SAMPLING_MODEL_IID_V1",
    "SharpeResult",
    "ValidationCandidate",
    "WalkForwardFold",
    "WalkForwardScheduleSpec",
    "as_training_dependency_evidence",
    "build_walk_forward_folds",
    "classify_candidate",
    "compute_moments_v1",
    "compute_sharpe_v1",
    "evaluate_dsr_v1",
    "evaluate_label",
    "evaluate_pbo_v1",
]
