"""Canonical derived representation runtimes."""

from .candles import (
    CANDLE_DEFINITION_V1_VERSION,
    CANDLE_RESULT_FINGERPRINT_V1_DOMAIN,
    CANDLE_V1_RECORD_SCHEMA,
    CandleComputationError,
    CandleCoverageError,
    CandleDefinitionV1,
    CandleFinalizationError,
    CandleInputError,
    CandleOrderingError,
    CandleProvenanceError,
    CandleRecord,
    HistoricalCandleCoverage,
    HistoricalCandleResult,
    HistoricalCandleSourceEvidence,
    aggregate_historical_candles,
    build_historical_candle_result,
    parse_duration_ns,
    required_bucket_support,
)

__all__ = [
    "CANDLE_DEFINITION_V1_VERSION",
    "CANDLE_RESULT_FINGERPRINT_V1_DOMAIN",
    "CANDLE_V1_RECORD_SCHEMA",
    "CandleComputationError",
    "CandleCoverageError",
    "CandleDefinitionV1",
    "CandleFinalizationError",
    "CandleInputError",
    "CandleOrderingError",
    "CandleProvenanceError",
    "CandleRecord",
    "HistoricalCandleCoverage",
    "HistoricalCandleResult",
    "HistoricalCandleSourceEvidence",
    "aggregate_historical_candles",
    "build_historical_candle_result",
    "parse_duration_ns",
    "required_bucket_support",
]
