"""Application-service composition seam.

This package owns composition of use cases that coordinate existing
capabilities without owning their domain semantics. It is an in-process seam:
it is not an API, a transport, or a client. It does not yet implement a job
runtime; ADR-0062 reserves future bounded J03 runtime composition to this
package without moving Experiment or other domain semantics here.

ASS-01 established ownership and enforcement.  C02 added semantic selector
resolution for the frozen ``trades@1`` reference representation.  C03 added
execution over an injected access capability and translation of its outcome
into a stable consumer result or one of the frozen Consumer API errors.
C05 adds typed immutable configuration and concrete composition for the current
market-data application service. Transport remains J02; J03 has an accepted
contract but no production implementation.
"""

from .backup_restore import (
    RECOVERY_MANIFEST_FILENAME,
    RECOVERY_MANIFEST_SCHEMA_VERSION,
    CatalogRestoreSession,
    PredecessorEvidence,
    RecoveryBackupExport,
    RestoreCatalog,
    RestoredRecoverySet,
    capture_recovery_set,
    export_recovery_set,
    load_recovery_backup_export,
    restore_recovery_set,
)
from .composition import (
    DEFAULT_MARKET_DATA_BATCH_SIZE,
    DEFAULT_MAX_RESULT_ROWS,
    MarketDataApplication,
    MarketDataApplicationConfig,
    compose_market_data_application,
)
from .durable_jobs import (
    DurableJobConflict,
    DurableJobError,
    DurableJobNotFound,
    DurableJobStore,
    EffectSafety,
    JobAdmission,
    JobAttempt,
    JobRecord,
    JobState,
    TERMINAL_JOB_STATES,
)
from .admitted_input import (
    AdmittedInputConflict,
    AdmittedInputError,
    AdmittedInputExpired,
    AdmittedInputManifestV1,
    AdmittedInputNotFound,
    AdmittedInputRecord,
    AdmittedInputState,
    AdmittedInputStore,
)
from .bybit_import import (
    CANONICAL_FIELD_ORDER,
    ImportError_,
    ImportReport,
    RECORD_SCHEMA_ID,
    SUPPORTED_CATEGORY,
    SUPPORTED_INSTRUMENT,
    SUPPORTED_VENUE,
    TradeStats,
    WriteResult,
    encode_record,
    format_exchange_ts,
    run_import,
    write_jsonl_atomic,
)
from .conformity import (
    Check,
    HarnessConfig,
    HarnessFailure,
    HarnessRunFailure,
    PreflightResult,
    RunReport,
    Target,
    VerificationMismatch,
    collect_preflight,
    inspect_vertical,
    run_vertical,
    verify_vertical,
)
from .h01_composition import (
    BUCKET_OBSERVATION_IDENTITY_DOMAIN,
    H01CompositionError,
    H01Evaluation,
    bucket_observation_identity,
    evaluate_h01_imbalance,
    materialize_h01_feature_artifact,
)
from .golden_conformity import (
    GoldenExpectation,
    ScanObservation,
    format_observation,
    golden_field_mismatches,
    load_golden_expectation,
    observe_scan,
)
from .market_data import (
    ApplicationRequestError,
    ConsumerApiError,
    ConsumerCoverage,
    ConsumerErrorCode,
    ConsumerMarketDataQuery,
    ConsumerMarketDataResult,
    ConsumerProvenance,
    NormalizedMarketDataQuery,
    RepresentationRef,
    UnsupportedOption,
    UnsupportedRepresentation,
    UnsupportedVenue,
    execute_market_data_query,
    resolve_market_data_request,
)
from .strategy_consumer import (
    STRATEGY_COMPOSE_REQUEST_IDENTITY_DOMAIN,
    StrategyComposeRequest,
    execute_strategy_compose,
)
from .api_transport_server import (
    ApiTransportServerConfig,
    J02_MAX_WIRE_MESSAGE_BYTES,
    J02_MARKET_DATA_READ_SCOPE,
    J02_REQUEST_SCHEMA_VERSION,
    J02_RESPONSE_SCHEMA_VERSION,
    RemoteJ02Principal,
    RemoteJ02SecurityConfig,
    RemoteJ02SecurityEvidence,
    RemoteJ02SecurityEvidenceLog,
    certificate_fingerprint,
    decode_transport_query,
    encode_consumer_error,
    encode_consumer_result,
    handle_api_transport_connection,
    handle_api_transport_message,
    run_api_transport_server,
)
from .golden_replay import (
    CANONICAL_BTCUSDT_DATASET,
    GoldenReplayProof,
    MinimalBreakoutFeatureProvider,
    NoOpExecutionPolicy,
    build_golden_replay_gateway,
    build_golden_replay_spec,
    minimal_breakout_strategy,
    run_golden_replay_proof,
)
from .golden_supervised import (
    DEFAULT_GOLDEN_FIXTURE,
    PRICE_DELTA_FEATURE_ID,
    WAVE5_GOLDEN_SUPERVISED_PROOF_VERSION,
    Wave5GoldenSupervisedProof,
    run_wave5_golden_supervised_proof,
)
from .live_candle_stream import (
    DEFAULT_LIVE_CANDLE_BATCH_SIZE,
    GapSafeLiveCandleComposer,
    LiveCandleStreamReport,
    compose_live_candle_stream,
)
from .storage_relocation import (
    PostgresRelocationCatalog,
    RelocationCatalog,
    RelocationCrashPoint,
    RelocationInterrupted,
    relocate_storage_tier,
)
from .retention_deletion import (
    InMemoryRetentionDeletionAuditStore,
    PostgresRetentionDeletionAuditStore,
    RetentionDeletionApplicationError,
    RetentionDeletionApplicationResult,
    RetentionDeletionAuditStore,
    RetentionDeletionCrashPoint,
    RetentionDeletionInterrupted,
    execute_retention_deletion,
    recover_retention_deletion_result,
)
from .wave6_golden import (
    WAVE6_CANONICAL_BTCUSDT_TRADES,
    WAVE6_DATASET_REL_ROOT,
    WAVE6_GOLDEN_E2E_PROOF_VERSION,
    Wave6GoldenE2EProof,
    run_wave6_golden_e2e_proof,
)

__all__ = [
    "BUCKET_OBSERVATION_IDENTITY_DOMAIN",
    "CANONICAL_BTCUSDT_DATASET",
    "CANONICAL_FIELD_ORDER",
    "DEFAULT_LIVE_CANDLE_BATCH_SIZE",
    "DEFAULT_MARKET_DATA_BATCH_SIZE",
    "DEFAULT_MAX_RESULT_ROWS",
    "AdmittedInputConflict",
    "AdmittedInputError",
    "AdmittedInputExpired",
    "AdmittedInputManifestV1",
    "AdmittedInputNotFound",
    "AdmittedInputRecord",
    "AdmittedInputState",
    "AdmittedInputStore",
    "DurableJobConflict",
    "DurableJobError",
    "DurableJobNotFound",
    "DurableJobStore",
    "EffectSafety",
    "ApplicationRequestError",
    "ApiTransportServerConfig",
    "Check",
    "ConsumerApiError",
    "ConsumerCoverage",
    "ConsumerErrorCode",
    "ConsumerMarketDataQuery",
    "ConsumerMarketDataResult",
    "ConsumerProvenance",
    "DEFAULT_GOLDEN_FIXTURE",
    "GoldenExpectation",
    "GoldenReplayProof",
    "GapSafeLiveCandleComposer",
    "H01CompositionError",
    "H01Evaluation",
    "HarnessConfig",
    "HarnessFailure",
    "HarnessRunFailure",
    "ImportError_",
    "ImportReport",
    "JobAdmission",
    "JobAttempt",
    "JobRecord",
    "JobState",
    "InMemoryRetentionDeletionAuditStore",
    "J02_MAX_WIRE_MESSAGE_BYTES",
    "J02_MARKET_DATA_READ_SCOPE",
    "J02_REQUEST_SCHEMA_VERSION",
    "J02_RESPONSE_SCHEMA_VERSION",
    "RemoteJ02Principal",
    "RemoteJ02SecurityConfig",
    "RemoteJ02SecurityEvidence",
    "RemoteJ02SecurityEvidenceLog",
    "MarketDataApplication",
    "MarketDataApplicationConfig",
    "LiveCandleStreamReport",
    "MinimalBreakoutFeatureProvider",
    "NoOpExecutionPolicy",
    "NormalizedMarketDataQuery",
    "RepresentationRef",
    "PreflightResult",
    "RECORD_SCHEMA_ID",
    "RECOVERY_MANIFEST_FILENAME",
    "RECOVERY_MANIFEST_SCHEMA_VERSION",
    "CatalogRestoreSession",
    "PredecessorEvidence",
    "PRICE_DELTA_FEATURE_ID",
    "PostgresRelocationCatalog",
    "PostgresRetentionDeletionAuditStore",
    "RecoveryBackupExport",
    "RestoreCatalog",
    "RestoredRecoverySet",
    "RelocationCatalog",
    "RelocationCrashPoint",
    "RelocationInterrupted",
    "RetentionDeletionApplicationError",
    "RetentionDeletionApplicationResult",
    "RetentionDeletionAuditStore",
    "RetentionDeletionCrashPoint",
    "RetentionDeletionInterrupted",
    "RunReport",
    "SUPPORTED_CATEGORY",
    "SUPPORTED_INSTRUMENT",
    "SUPPORTED_VENUE",
    "ScanObservation",
    "STRATEGY_COMPOSE_REQUEST_IDENTITY_DOMAIN",
    "StrategyComposeRequest",
    "Target",
    "TERMINAL_JOB_STATES",
    "TradeStats",
    "UnsupportedOption",
    "UnsupportedRepresentation",
    "UnsupportedVenue",
    "WAVE5_GOLDEN_SUPERVISED_PROOF_VERSION",
    "WAVE6_CANONICAL_BTCUSDT_TRADES",
    "WAVE6_DATASET_REL_ROOT",
    "WAVE6_GOLDEN_E2E_PROOF_VERSION",
    "Wave5GoldenSupervisedProof",
    "Wave6GoldenE2EProof",
    "VerificationMismatch",
    "WriteResult",
    "bucket_observation_identity",
    "build_golden_replay_gateway",
    "build_golden_replay_spec",
    "capture_recovery_set",
    "collect_preflight",
    "compose_live_candle_stream",
    "compose_market_data_application",
    "encode_record",
    "evaluate_h01_imbalance",
    "execute_market_data_query",
    "execute_strategy_compose",
    "decode_transport_query",
    "certificate_fingerprint",
    "encode_consumer_error",
    "encode_consumer_result",
    "execute_retention_deletion",
    "export_recovery_set",
    "format_exchange_ts",
    "format_observation",
    "golden_field_mismatches",
    "handle_api_transport_connection",
    "handle_api_transport_message",
    "inspect_vertical",
    "load_golden_expectation",
    "load_recovery_backup_export",
    "materialize_h01_feature_artifact",
    "minimal_breakout_strategy",
    "observe_scan",
    "resolve_market_data_request",
    "restore_recovery_set",
    "relocate_storage_tier",
    "recover_retention_deletion_result",
    "run_golden_replay_proof",
    "run_wave5_golden_supervised_proof",
    "run_wave6_golden_e2e_proof",
    "run_import",
    "run_api_transport_server",
    "run_vertical",
    "verify_vertical",
    "write_jsonl_atomic",
]
